// app/src/components/Overview.jsx
import { STATUS, STATUS_ORDER, isDone } from '../data/mockData'

function DensityRow({ tasks }) {
  const sorted = [...tasks].sort(
    (a, b) => STATUS_ORDER.indexOf(b.status) - STATUS_ORDER.indexOf(a.status)
  )
  return (
    <div className="h-2 flex border border-slate-200 bg-white rounded-sm overflow-hidden">
      {sorted.map(t => (
        <div
          key={t.id}
          className="density-cell"
          style={{ backgroundColor: STATUS[t.status].bar }}
          title={`#${t.examId} · ${STATUS[t.status].label}`}
        />
      ))}
    </div>
  )
}

export default function Overview({ tasks, totalExams }) {
  const total = tasks.length
  const counts = STATUS_ORDER.reduce((acc, s) => {
    acc[s] = tasks.filter(t => t.status === s).length
    return acc
  }, {})

  const accepted = tasks.filter(t => isDone(t.status)).length
  const pct      = total ? Math.round((accepted / total) * 100) : 0
  const subjects = new Set(tasks.map(t => t.subjectId)).size
  const unassignedExams = totalExams - new Set(tasks.map(t => t.examId)).size

  return (
    <div className="card">
      <div className="flex divide-x divide-slate-200">
        <div className="metric flex-1">
          <div className="metric-label">Accepted</div>
          <div className="flex items-baseline gap-1.5">
            <span className="metric-value text-brand-700">{pct}%</span>
            <span className="caption num">{accepted}/{total}</span>
          </div>
        </div>
        <div className="metric flex-1">
          <div className="metric-label">Submitted</div>
          <div className="flex items-baseline gap-1.5">
            <span className="metric-value">{counts.submitted}</span>
            <span className="caption">awaiting review</span>
          </div>
        </div>
        <div className="metric flex-1">
          <div className="metric-label">In progress</div>
          <div className="flex items-baseline gap-1.5">
            <span className="metric-value">{counts.in_progress}</span>
            <span className="caption">active</span>
          </div>
        </div>
        <div className="metric flex-1">
          <div className="metric-label">Revisions</div>
          <div className="flex items-baseline gap-1.5">
            <span className="metric-value">{counts.revisions}</span>
            <span className="caption">returned</span>
          </div>
        </div>
        <div className="metric flex-1">
          <div className="metric-label">To do</div>
          <div className="flex items-baseline gap-1.5">
            <span className="metric-value">{counts.todo}</span>
            <span className="caption num">{subjects} subj · {unassignedExams} unassigned</span>
          </div>
        </div>
      </div>

      <div className="px-4 pb-3 pt-1">
        <DensityRow tasks={tasks} />
        <div className="flex justify-between items-center mt-1.5">
          <div className="flex items-center gap-3 caption">
            {STATUS_ORDER.map(s => (
              <span key={s} className="inline-flex items-center gap-1">
                <span className="w-2 h-2 rounded-sm" style={{ backgroundColor: STATUS[s].bar }} />
                {STATUS[s].label}
              </span>
            ))}
          </div>
          <span className="caption">1 cell ≈ 1 task</span>
        </div>
      </div>
    </div>
  )
}

// angular/src/app/annotations/overview.component.ts
import { Component, computed, input } from '@angular/core';
import { STATUS, STATUS_ORDER, isDone } from '../data/mock-data';
import { StatusId, Task } from '../data/models';

@Component({
  selector: 'app-overview',
  template: `
    <div class="card">
      <div class="metrics">
        <div class="metric">
          <div class="metric-label">Accepted</div>
          <div class="row">
            <span class="metric-value" style="color: var(--brand)">{{ pct() }}%</span>
            <span class="caption num">{{ accepted() }}/{{ total() }}</span>
          </div>
        </div>
        <div class="metric">
          <div class="metric-label">Submitted</div>
          <div class="row"><span class="metric-value">{{ counts()['submitted'] }}</span><span class="caption">awaiting review</span></div>
        </div>
        <div class="metric">
          <div class="metric-label">In progress</div>
          <div class="row"><span class="metric-value">{{ counts()['in_progress'] }}</span><span class="caption">active</span></div>
        </div>
        <div class="metric">
          <div class="metric-label">Revisions</div>
          <div class="row"><span class="metric-value">{{ counts()['revisions'] }}</span><span class="caption">returned</span></div>
        </div>
        <div class="metric">
          <div class="metric-label">To do</div>
          <div class="row"><span class="metric-value">{{ counts()['todo'] }}</span><span class="caption num">{{ subjects() }} subj · {{ unassignedExams() }} unassigned</span></div>
        </div>
      </div>

      <div class="density-wrap">
        <div class="density-row">
          @for (t of sorted(); track t.id) {
            <div class="density-cell" [style.background]="STATUS[t.status].bar" [title]="'#' + t.examId + ' · ' + STATUS[t.status].label"></div>
          }
        </div>
        <div class="legend">
          <div class="keys">
            @for (s of STATUS_ORDER; track s) {
              <span class="key"><span class="sw" [style.background]="STATUS[s].bar"></span>{{ STATUS[s].label }}</span>
            }
          </div>
          <span class="caption">1 cell ≈ 1 task</span>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .metrics { display: flex; }
    .metric { flex: 1; }
    .row { display: flex; align-items: baseline; gap: 6px; }
    .density-wrap { padding: 4px 14px 12px; }
    .density-row { height: 8px; display: flex; border: 1px solid var(--grey-border); background: #fff; border-radius: 2px; overflow: hidden; }
    .legend { display: flex; justify-content: space-between; align-items: center; margin-top: 6px; }
    .keys { display: flex; gap: 12px; }
    .key { display: inline-flex; align-items: center; gap: 4px; font-size: 11px; color: var(--grey-mid); }
    .sw { width: 8px; height: 8px; border-radius: 2px; display: inline-block; }
  `],
})
export class Overview {
  tasks = input.required<Task[]>();
  totalExams = input.required<number>();
  readonly STATUS = STATUS;
  readonly STATUS_ORDER = STATUS_ORDER;

  total = computed(() => this.tasks().length);
  counts = computed<Record<StatusId, number>>(() =>
    STATUS_ORDER.reduce((acc, s) => {
      acc[s] = this.tasks().filter(t => t.status === s).length;
      return acc;
    }, {} as Record<StatusId, number>));
  accepted = computed(() => this.tasks().filter(t => isDone(t.status)).length);
  pct = computed(() => this.total() ? Math.round((this.accepted() / this.total()) * 100) : 0);
  subjects = computed(() => new Set(this.tasks().map(t => t.subjectId)).size);
  unassignedExams = computed(() => this.totalExams() - new Set(this.tasks().map(t => t.examId)).size);
  sorted = computed(() =>
    [...this.tasks()].sort((a, b) => STATUS_ORDER.indexOf(b.status) - STATUS_ORDER.indexOf(a.status)));
}
