// app/src/components/TaskTable.jsx
import { Fragment } from 'react'
import {
  EXAMINATIONS, STATUS,
  examById, userById,
  ohifViewUrl, shanoirExamUrl,
} from '../data/mockData'

const StatusMark = ({ status }) => {
  const m = STATUS[status]
  return (
    <span className="mark">
      <span className="mark-dot" style={{ backgroundColor: m.bar }} />
      <span className="text-slate-700">{m.label}</span>
    </span>
  )
}

const ProjectPip = ({ project }) => {
  if (!project) return <span className="caption italic">—</span>
  return (
    <span className="inline-flex items-center gap-1.5 text-[12px] text-slate-700">
      <span className="w-2 h-2 rounded-sm" style={{ backgroundColor: project.color }} />
      <span className="truncate max-w-[140px]">{project.name}</span>
      <span className="text-[9px] font-mono uppercase px-1 py-px rounded bg-slate-100 text-slate-500">
        {project.type === 'text' ? 'txt' : 'seg'}
      </span>
    </span>
  )
}

function ReplicaStrip({ tasksForExam }) {
  if (tasksForExam.length === 0) return <span className="caption italic">—</span>
  return (
    <span className="inline-flex items-center gap-1">
      {tasksForExam.map(t => {
        const u = userById(t.assigneeId)
        return (
          <span
            key={t.id}
            title={`${u?.handle ?? '?'} · ${STATUS[t.status].label}`}
            className="inline-flex items-center justify-center w-5 h-5 text-[9px] font-medium uppercase rounded-full text-white"
            style={{ backgroundColor: STATUS[t.status].bar }}
          >
            {u?.initials ?? '?'}
          </span>
        )
      })}
    </span>
  )
}

export default function TaskTable({
  tasks, allTasks, currentUser, projectsById,
  selectedIds, onSelect, onSelectAll, onSelectSubject,
  onStatusChange, onUnassign, onReview, onAnnotate,
}) {
  const isManager = currentUser.role === 'manager'

  const grouped = []
  const subjectIndex = {}
  tasks.forEach(t => {
    if (!(t.subjectId in subjectIndex)) {
      subjectIndex[t.subjectId] = grouped.length
      grouped.push({ subjectId: t.subjectId, tasks: [] })
    }
    grouped[subjectIndex[t.subjectId]].tasks.push(t)
  })

  if (tasks.length === 0) {
    return (
      <div className="card p-12 text-center">
        <div className="text-slate-700 text-[15px] font-medium mb-1">No tasks match the filters</div>
        <div className="caption">Adjust the sidebar filters, or create tasks from the Projects tab.</div>
      </div>
    )
  }

  const allSelected = tasks.length > 0 && tasks.every(t => selectedIds.includes(t.id))

  return (
    <div className="card overflow-hidden">
      <div className="overflow-x-auto">
        <table className="data-table">
          <thead>
            <tr>
              <th className="w-8 pl-4">
                {isManager && <input type="checkbox" checked={allSelected} onChange={e => onSelectAll(e.target.checked)} />}
              </th>
              <th>Examination</th>
              <th>Date</th>
              <th>Project</th>
              <th>Assignee</th>
              <th>Status</th>
              <th>Output</th>
              <th>Replicas</th>
              <th className="text-right pr-4">Actions</th>
            </tr>
          </thead>
          <tbody>
            {grouped.map(({ subjectId, tasks: rows }) => {
              const subjectExams = EXAMINATIONS.filter(e => e.subjectId === subjectId)
              const allRowsForSubject = allTasks.filter(t => t.subjectId === subjectId)
              const subjectTaskIds = rows.map(r => r.id)
              const subjectAllSelected = subjectTaskIds.length > 0 && subjectTaskIds.every(id => selectedIds.includes(id))

              return (
                <Fragment key={subjectId}>
                  <tr className="group-row">
                    <td colSpan={9} className="pl-4">
                      <div className="flex items-baseline justify-between gap-4">
                        <div className="flex items-baseline gap-2">
                          <span className="label">Subject</span>
                          <span className="font-mono text-[13px] text-slate-900 num">{subjectId}</span>
                          <span className="caption">· {subjectExams.length} exam{subjectExams.length !== 1 ? 's' : ''} · {allRowsForSubject.length} task{allRowsForSubject.length !== 1 ? 's' : ''}</span>
                        </div>
                        {isManager && (
                          <button onClick={() => onSelectSubject(subjectId, !subjectAllSelected)} className="caption hover:text-brand-700 hover:underline">
                            {subjectAllSelected ? 'Deselect subject' : 'Select all in subject'}
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>

                  {rows.map(task => {
                    const exam = examById(task.examId)
                    const u = userById(task.assigneeId)
                    const isSelected = selectedIds.includes(task.id)
                    const isAssigned = task.assigneeId === currentUser.id
                    const replicas = allTasks.filter(t => t.examId === task.examId && t.projectId === task.projectId && t.id !== task.id)
                    const project = projectsById[task.projectId]
                    const isText = project?.type === 'text'
                    const segCount = task.submissions.filter(f => f.kind === 'seg').length
                    const pngCount = task.submissions.filter(f => f.kind === 'screenshot').length
                    const answerCount = Object.values(task.answers || {}).filter(v => v && v.trim()).length

                    return (
                      <tr key={task.id} className={isSelected ? 'selected' : ''}>
                        <td className="pl-4">
                          {isManager && <input type="checkbox" checked={isSelected} onChange={e => onSelect(task.id, e.target.checked)} />}
                        </td>

                        <td>
                          <div className="leading-tight">
                            <div className="flex items-center gap-2">
                              <a href={shanoirExamUrl(task.examId)} target="_blank" rel="noreferrer" className="link num font-mono text-[13px]">#{task.examId}</a>
                              <span className="text-[12px] text-slate-500">· {exam.series.length} series</span>
                            </div>
                            <div className="caption mt-0.5 truncate max-w-[260px]" title={exam.series.join(', ')}>
                              {exam.series.slice(0, 3).join(' · ')}{exam.series.length > 3 && ` · +${exam.series.length - 3}`}
                            </div>
                          </div>
                        </td>

                        <td className="font-mono text-[12px] text-slate-600 num">{exam.date}</td>

                        <td><ProjectPip project={project} /></td>

                        <td>
                          {u ? (
                            <div className="inline-flex items-center gap-2">
                              <span className={`avatar avatar-sm avatar-${u.tone}`}>{u.initials}</span>
                              <span className="text-slate-800 text-[13px]">{u.handle}</span>
                              {isManager && (
                                <button onClick={() => onUnassign(task.id)} title="Remove task" className="ml-1 text-slate-400 hover:text-red-600 text-sm leading-none">✕</button>
                              )}
                            </div>
                          ) : <span className="caption italic">unassigned</span>}
                        </td>

                        {/* Status — manager-only editable */}
                        <td>
                          {isManager ? (
                            <select
                              value={task.status}
                              onChange={e => onStatusChange(task.id, e.target.value)}
                              className="bg-transparent border-none text-[13px] cursor-pointer focus:outline-none focus:ring-1 focus:ring-brand-600/30 rounded px-1 py-0.5"
                              style={{ color: STATUS[task.status].bar }}
                            >
                              {Object.values(STATUS).map(s => (
                                <option key={s.id} value={s.id} className="text-slate-900">{s.label}</option>
                              ))}
                            </select>
                          ) : (
                            <StatusMark status={task.status} />
                          )}
                        </td>

                        {/* Output */}
                        <td>
                          {isText ? (
                            answerCount > 0
                              ? <span className="inline-flex items-center gap-1 text-[12px] text-slate-700"><span className="font-mono text-[9px] uppercase px-1.5 py-0.5 rounded bg-slate-200 text-slate-700">TXT</span><span className="num">{answerCount}/{project.fields?.length || 0}</span></span>
                              : <span className="caption">—</span>
                          ) : (
                            (segCount + pngCount === 0)
                              ? <span className="caption">—</span>
                              : (
                                <span className="inline-flex items-center gap-2 text-[12px] text-slate-700">
                                  {segCount > 0 && <span className="inline-flex items-center gap-1"><span className="font-mono text-[9px] uppercase px-1.5 py-0.5 rounded bg-slate-200 text-slate-700">SEG</span><span className="num">{segCount}</span></span>}
                                  {pngCount > 0 && <span className="inline-flex items-center gap-1"><span className="font-mono text-[9px] uppercase px-1.5 py-0.5 rounded bg-slate-200 text-slate-700">IMG</span><span className="num">{pngCount}</span></span>}
                                </span>
                              )
                          )}
                        </td>

                        <td><ReplicaStrip tasksForExam={replicas} /></td>

                        <td className="pr-4 text-right">
                          <div className="inline-flex items-center gap-1.5 justify-end">
                            {!isText && (
                              <a href={ohifViewUrl(exam.studyInstanceUID)} target="_blank" rel="noreferrer" className="btn btn-sm btn-ghost" title="Open OHIF (read-only)">View</a>
                            )}
                            {(isManager || isAssigned) && task.status !== 'accepted' && (
                              <button onClick={() => onAnnotate(task.id)} className="btn btn-sm btn-primary" title="Open the annotation task">
                                {isText ? 'Write' : 'Annotate'}
                              </button>
                            )}
                            {(isManager || isAssigned) && task.status === 'accepted' && (
                              <button onClick={() => onAnnotate(task.id)} className="btn btn-sm btn-ghost">Open</button>
                            )}
                            {isManager && replicas.some(r => r.submissions.length > 0 || Object.keys(r.answers || {}).length > 0) && (
                              <button onClick={() => onReview(task.examId, task.projectId)} className="btn btn-sm btn-secondary" title="Review all submissions for this examination">Review</button>
                            )}
                          </div>
                        </td>
                      </tr>
                    )
                  })}
                </Fragment>
              )
            })}
          </tbody>
        </table>
      </div>
    </div>
  )
}

// angular/src/app/annotations/task-table.component.ts
import { Component, computed, inject } from '@angular/core';
import { AppStore } from '../core/app.store';
import {
  EXAMINATIONS, STATUS, examById, userById, ohifViewUrl, shanoirExamUrl,
} from '../data/mock-data';
import { Project, StatusId, Task, User } from '../data/models';
import { StatusMark } from '../shared/status-mark.component';
import { Avatar } from '../shared/avatar.component';
import { ReplicaStrip } from '../shared/replica-strip.component';

interface Group { subjectId: string; rows: Task[]; }

@Component({
  selector: 'app-task-table',
  imports: [StatusMark, Avatar, ReplicaStrip],
  templateUrl: './task-table.component.html',
  styleUrl: './task-table.component.css',
})
export class TaskTable {
  store = inject(AppStore);
  readonly STATUS = STATUS;
  readonly statusList = Object.values(STATUS);

  isManager = computed(() => this.store.currentUser().role === 'manager');
  filtered = computed(() => this.store.filtered());
  allTasks = computed(() => this.store.tasks());
  selectedIds = computed(() => this.store.selectedIds());

  grouped = computed<Group[]>(() => {
    const out: Group[] = [];
    const idx: Record<string, number> = {};
    for (const t of this.filtered()) {
      if (!(t.subjectId in idx)) { idx[t.subjectId] = out.length; out.push({ subjectId: t.subjectId, rows: [] }); }
      out[idx[t.subjectId]].rows.push(t);
    }
    return out;
  });

  allSelected = computed(() =>
    this.filtered().length > 0 && this.filtered().every(t => this.selectedIds().includes(t.id)));

  // ─── per-row derivations ───────────────────────────────────────────────────
  exam = (t: Task) => examById(t.examId)!;
  user = (t: Task): User | null => userById(t.assigneeId);
  project = (t: Task): Project | undefined => this.store.projectsById()[t.projectId];
  isText = (t: Task) => this.project(t)?.type === 'text';
  isSelected = (t: Task) => this.selectedIds().includes(t.id);
  isAssigned = (t: Task) => t.assigneeId === this.store.currentUser().id;
  replicas = (t: Task) =>
    this.allTasks().filter(x => x.examId === t.examId && x.projectId === t.projectId && x.id !== t.id);
  segCount = (t: Task) => t.submissions.filter(f => f.kind === 'seg').length;
  pngCount = (t: Task) => t.submissions.filter(f => f.kind === 'screenshot').length;
  answerCount = (t: Task) => Object.values(t.answers ?? {}).filter(v => v && v.trim()).length;
  fieldCount = (t: Task) => this.project(t)?.fields?.length ?? 0;
  canReview = (t: Task) => this.isManager() &&
    this.replicas(t).some(r => r.submissions.length > 0 || Object.keys(r.answers ?? {}).length > 0);
  canWork = (t: Task) => this.isManager() || this.isAssigned(t);

  seriesPreview = (t: Task) => {
    const s = this.exam(t).series;
    return s.slice(0, 3).join(' · ') + (s.length > 3 ? ` · +${s.length - 3}` : '');
  };
  seriesTitle = (t: Task) => this.exam(t).series.join(', ');

  // ─── subject group helpers ─────────────────────────────────────────────────
  subjectExamCount = (subjectId: string) => EXAMINATIONS.filter(e => e.subjectId === subjectId).length;
  subjectTaskCount = (subjectId: string) => this.allTasks().filter(t => t.subjectId === subjectId).length;
  subjectAllSelected = (rows: Task[]) => rows.length > 0 && rows.every(r => this.selectedIds().includes(r.id));

  // ─── links / actions ───────────────────────────────────────────────────────
  shanoirExamUrl = shanoirExamUrl;
  ohifUrl = (t: Task) => ohifViewUrl(this.exam(t).studyInstanceUID);

  onSelect(t: Task, e: Event): void { this.store.select(t.id, (e.target as HTMLInputElement).checked); }
  onSelectAll(e: Event): void { this.store.selectAll((e.target as HTMLInputElement).checked); }
  onStatus(t: Task, e: Event): void { this.store.statusChange(t.id, (e.target as HTMLSelectElement).value as StatusId); }
}

@if (filtered().length === 0) {
  <div class="card empty">
    <div class="empty-title">No tasks match the filters</div>
    <div class="caption">Adjust the sidebar filters, or create tasks from the Projects tab.</div>
  </div>
} @else {
  <div class="card table-wrap">
    <table class="data-table">
      <thead>
        <tr>
          <th class="w-chk">
            @if (isManager()) {
              <input type="checkbox" [checked]="allSelected()" (change)="onSelectAll($event)" />
            }
          </th>
          <th>Examination</th>
          <th>Date</th>
          <th>Project</th>
          <th>Assignee</th>
          <th>Status</th>
          <th>Output</th>
          <th>Replicas</th>
          <th class="ar">Actions</th>
        </tr>
      </thead>
      <tbody>
        @for (g of grouped(); track g.subjectId) {
          <tr class="group-row">
            <td colspan="9">
              <div class="group-head">
                <div class="group-id">
                  <span class="label">Subject</span>
                  <span class="num subj">{{ g.subjectId }}</span>
                  <span class="caption">· {{ subjectExamCount(g.subjectId) }} exam{{ subjectExamCount(g.subjectId) !== 1 ? 's' : '' }} · {{ subjectTaskCount(g.subjectId) }} task{{ subjectTaskCount(g.subjectId) !== 1 ? 's' : '' }}</span>
                </div>
                @if (isManager()) {
                  <button class="link-btn caption" (click)="store.selectSubject(g.subjectId, !subjectAllSelected(g.rows))">
                    {{ subjectAllSelected(g.rows) ? 'Deselect subject' : 'Select all in subject' }}
                  </button>
                }
              </div>
            </td>
          </tr>

          @for (t of g.rows; track t.id) {
            <tr [class.selected]="isSelected(t)">
              <td>
                @if (isManager()) {
                  <input type="checkbox" [checked]="isSelected(t)" (change)="onSelect(t, $event)" />
                }
              </td>

              <td>
                <div class="exam">
                  <div class="exam-top">
                    <a [href]="shanoirExamUrl(t.examId)" target="_blank" rel="noreferrer" class="link num mono">#{{ t.examId }}</a>
                    <span class="caption">· {{ exam(t).series.length }} series</span>
                  </div>
                  <div class="caption series" [title]="seriesTitle(t)">{{ seriesPreview(t) }}</div>
                </div>
              </td>

              <td class="mono caption num">{{ exam(t).date }}</td>

              <td>
                @if (project(t); as p) {
                  <span class="pip"><span class="sw" [style.background]="p.color"></span><span class="pname">{{ p.name }}</span><span class="tag">{{ p.type === 'text' ? 'txt' : 'seg' }}</span></span>
                } @else { <span class="caption"><em>—</em></span> }
              </td>

              <td>
                @if (user(t); as u) {
                  <span class="assignee">
                    <app-avatar [user]="u" size="sm" /><span class="handle">{{ u.handle }}</span>
                    @if (isManager()) {
                      <button class="x" title="Remove task" (click)="store.unassign(t.id)">✕</button>
                    }
                  </span>
                } @else { <span class="caption"><em>unassigned</em></span> }
              </td>

              <td>
                @if (isManager()) {
                  <select class="status-select" [style.color]="STATUS[t.status].bar" (change)="onStatus(t, $event)">
                    @for (s of statusList; track s.id) { <option [value]="s.id" [selected]="s.id === t.status">{{ s.label }}</option> }
                  </select>
                } @else {
                  <app-status-mark [status]="t.status" />
                }
              </td>

              <td>
                @if (isText(t)) {
                  @if (answerCount(t) > 0) {
                    <span class="out"><span class="badge">TXT</span><span class="num">{{ answerCount(t) }}/{{ fieldCount(t) }}</span></span>
                  } @else { <span class="caption">—</span> }
                } @else {
                  @if (segCount(t) + pngCount(t) === 0) {
                    <span class="caption">—</span>
                  } @else {
                    <span class="out">
                      @if (segCount(t) > 0) { <span class="badge">SEG</span><span class="num">{{ segCount(t) }}</span> }
                      @if (pngCount(t) > 0) { <span class="badge">IMG</span><span class="num">{{ pngCount(t) }}</span> }
                    </span>
                  }
                }
              </td>

              <td><app-replica-strip [tasks]="replicas(t)" /></td>

              <td class="ar">
                <div class="row-actions">
                  @if (!isText(t)) {
                    <a [href]="ohifUrl(t)" target="_blank" rel="noreferrer" class="btn btn-sm btn-ghost" title="Open OHIF (read-only)">View</a>
                  }
                  @if (canWork(t) && t.status !== 'accepted') {
                    <button class="btn btn-sm btn-primary" (click)="store.openAnnotate(t.id)">{{ isText(t) ? 'Write' : 'Annotate' }}</button>
                  }
                  @if (canWork(t) && t.status === 'accepted') {
                    <button class="btn btn-sm btn-ghost" (click)="store.openAnnotate(t.id)">Open</button>
                  }
                  @if (canReview(t)) {
                    <button class="btn btn-sm btn-secondary" (click)="store.openReview(t.examId, t.projectId)" title="Review all submissions">Review</button>
                  }
                </div>
              </td>
            </tr>
          }
        }
      </tbody>
    </table>
  </div>
}
