// angular/src/app/overlays/review-drawer.component.ts
import { Component, HostListener, computed, inject } from '@angular/core';
import { AppStore } from '../core/app.store';
import {
  STATUS, examById, ohifAnnotateUrl, ohifViewUrl, shanoirExamUrl, userById,
} from '../data/mock-data';
import { Submission, Task } from '../data/models';
import { Avatar } from '../shared/avatar.component';
import { BytesPipe } from '../shared/format.pipes';

@Component({
  selector: 'app-review-drawer',
  imports: [Avatar, BytesPipe],
  templateUrl: './review-drawer.component.html',
  styleUrl: './review-drawer.component.css',
})
export class ReviewDrawer {
  store = inject(AppStore);
  readonly STATUS = STATUS;
  readonly userById = userById;
  readonly shanoirExamUrl = shanoirExamUrl;

  review = computed(() => this.store.review());
  exam = computed(() => { const r = this.review(); return r ? examById(r.examId) : undefined; });
  project = computed(() => { const r = this.review(); return r ? this.store.projectsById()[r.projectId] : undefined; });
  isText = computed(() => this.project()?.type === 'text');
  tasks = computed<Task[]>(() => {
    const r = this.review();
    return r ? this.store.tasks().filter(t => t.examId === r.examId && t.projectId === r.projectId) : [];
  });

  ohifView = computed(() => { const e = this.exam(); return e ? ohifViewUrl(e.studyInstanceUID) : '#'; });
  ohifEdit = computed(() => { const e = this.exam(); return e ? ohifAnnotateUrl(e.studyInstanceUID) : '#'; });

  files = (t: Task): Submission[] => [
    ...t.submissions.filter(f => f.kind === 'seg'),
    ...t.submissions.filter(f => f.kind === 'screenshot'),
  ];
  hasAnswers = (t: Task) => Object.values(t.answers ?? {}).some(v => v && v.trim());

  close(): void { this.store.closeReview(); }
  setStatus(id: string, status: 'accepted' | 'revisions' | 'submitted'): void { this.store.statusChange(id, status); }

  @HostListener('document:keydown.escape')
  onEscape(): void { if (this.review()) this.close(); }
}

@if (review() && exam(); as _) {
  <div class="backdrop" (click)="close()">
    <div class="drawer" (click)="$event.stopPropagation()">
      <div class="head">
        <div class="head-top">
          <div>
            <div class="proj"><span class="sw" [style.background]="project()?.color"></span><span class="label">Review · {{ project()?.name }}</span></div>
            <h3>Compare annotations</h3>
            <div class="caption sub">
              Subject <span class="mono">{{ exam()!.subjectId }}</span> ·
              <a [href]="shanoirExamUrl(exam()!.examId)" target="_blank" rel="noreferrer" class="link">exam #{{ exam()!.examId }}</a> ·
              {{ exam()!.date }} · {{ exam()!.series.length }} series
            </div>
          </div>
          <button class="btn btn-ghost btn-sm" (click)="close()">✕</button>
        </div>
        @if (!isText()) {
          <div class="ohif">
            <a [href]="ohifView()" target="_blank" rel="noreferrer" class="btn btn-primary">View in OHIF</a>
            <a [href]="ohifEdit()" target="_blank" rel="noreferrer" class="btn btn-secondary">Segmentation editor</a>
          </div>
        }
      </div>

      <div class="body">
        @if (tasks().length === 0) { <div class="caption">No annotators assigned.</div> }
        @for (t of tasks(); track t.id) {
          <article class="card sub-card">
            <header class="sc-head">
              <div class="who">
                <app-avatar [user]="userById(t.assigneeId)" size="lg" />
                <div>
                  <div class="handle">{{ userById(t.assigneeId)?.handle }}</div>
                  <div class="caption">{{ userById(t.assigneeId)?.role }} · updated {{ t.updatedAt }}</div>
                </div>
              </div>
              <span class="mark"><span class="mark-dot" [style.background]="STATUS[t.status].bar"></span>{{ STATUS[t.status].label }}</span>
            </header>

            @if (isText()) {
              @if (hasAnswers(t)) {
                <div class="answers">
                  @for (f of project()!.fields; track f.id) {
                    <div>
                      <div class="label mb">{{ f.label }}</div>
                      <div class="answer">
                        @if (t.answers[f.id] && t.answers[f.id].trim()) { {{ t.answers[f.id] }} } @else { <span class="muted">— empty —</span> }
                      </div>
                    </div>
                  }
                </div>
              } @else { <div class="caption none">No answers yet.</div> }
            } @else {
              @if (t.submissions.length === 0) { <div class="caption none">No files uploaded yet.</div> }
              @else {
                <div class="files">
                  @for (f of files(t); track f.filename) {
                    <div class="file-row">
                      <span class="badge">{{ f.kind === 'seg' ? 'SEG' : 'IMG' }}</span>
                      <span class="mono fn">{{ f.filename }}</span>
                      <span class="caption num">{{ f.size | bytes }}</span>
                    </div>
                  }
                </div>
              }
            }

            <div class="actions">
              @if (t.status === 'submitted') {
                <button class="btn btn-sm btn-alt" (click)="setStatus(t.id, 'accepted')">✓ Accept</button>
                <button class="btn btn-sm btn-danger" (click)="setStatus(t.id, 'revisions')">Request revisions</button>
              }
              @if (t.status === 'accepted') { <span class="caption ok">✓ Accepted</span> }
              @if (t.status === 'revisions') { <span class="caption err">Revisions requested</span> }
              @if (t.status === 'todo' || t.status === 'in_progress') {
                <button class="btn btn-sm btn-secondary" (click)="setStatus(t.id, 'submitted')">Mark submitted</button>
              }
            </div>
          </article>
        }
      </div>

      <div class="foot caption">esc to close</div>
    </div>
  </div>
}

// app/src/components/ReviewDrawer.jsx
import { useEffect } from 'react'
import {
  examById, userById, STATUS,
  ohifAnnotateUrl, ohifViewUrl, shanoirExamUrl, formatBytes,
} from '../data/mockData'

export default function ReviewDrawer({ review, allTasks, projectsById, onClose, onStatusChange }) {
  useEffect(() => {
    const k = e => { if (e.key === 'Escape') onClose() }
    window.addEventListener('keydown', k)
    return () => window.removeEventListener('keydown', k)
  }, [onClose])

  if (!review) return null

  const { examId, projectId } = review
  const exam    = examById(examId)
  const project = projectsById[projectId]
  const isText  = project?.type === 'text'
  const tasks   = allTasks.filter(t => t.examId === examId && t.projectId === projectId)

  return (
    <div className="fixed inset-0 z-50 flex justify-end animate-fadeIn">
      <div className="absolute inset-0 bg-slate-900/40" onClick={onClose} />

      <div className="relative w-[680px] max-w-[94vw] bg-white border-l border-slate-200 shadow-xl overflow-y-auto animate-riseIn">
        <div className="px-6 py-5 border-b border-slate-200 sticky top-0 bg-white z-10">
          <div className="flex items-start justify-between gap-4">
            <div>
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-sm" style={{ backgroundColor: project?.color }} />
                <div className="label">Review · {project?.name}</div>
              </div>
              <h3 className="text-[18px] font-semibold text-slate-900 mt-0.5">Compare annotations</h3>
              <div className="caption mt-1">
                Subject <span className="font-mono text-slate-700 num">{exam.subjectId}</span>
                {' · '}
                <a href={shanoirExamUrl(examId)} target="_blank" rel="noreferrer" className="link num">exam #{examId}</a>
                {' · '}{exam.date} · {exam.series.length} series
              </div>
            </div>
            <button onClick={onClose} className="btn btn-ghost btn-sm">✕</button>
          </div>

          {!isText && (
            <div className="mt-4 flex items-center gap-2">
              <a href={ohifViewUrl(exam.studyInstanceUID)} target="_blank" rel="noreferrer" className="btn btn-primary">View in OHIF</a>
              <a href={ohifAnnotateUrl(exam.studyInstanceUID)} target="_blank" rel="noreferrer" className="btn btn-secondary">Segmentation editor</a>
            </div>
          )}
        </div>

        <div className="px-6 py-5 space-y-3">
          {tasks.length === 0 && <div className="caption">No annotators assigned.</div>}

          {tasks.map(t => {
            const u = userById(t.assigneeId)
            const s = STATUS[t.status]
            const segs = t.submissions.filter(f => f.kind === 'seg')
            const pngs = t.submissions.filter(f => f.kind === 'screenshot')
            return (
              <article key={t.id} className="card p-4">
                <header className="flex items-start justify-between gap-3 mb-3">
                  <div className="flex items-center gap-2.5">
                    <span className={`avatar avatar-${u?.tone || 'ink'}`}>{u?.initials || '?'}</span>
                    <div className="leading-tight">
                      <div className="text-[13px] font-medium text-slate-900">{u?.handle}</div>
                      <div className="caption">{u?.role} · updated {t.updatedAt}</div>
                    </div>
                  </div>
                  <span className="mark"><span className="mark-dot" style={{ backgroundColor: s.bar }} />{s.label}</span>
                </header>

                {isText ? (
                  /* text answers */
                  Object.values(t.answers || {}).some(v => v && v.trim()) ? (
                    <div className="space-y-2.5 mb-3">
                      {project.fields.map(f => (
                        <div key={f.id}>
                          <div className="label mb-0.5">{f.label}</div>
                          <div className="text-[13px] text-slate-800 whitespace-pre-wrap bg-slate-50 border border-slate-200 rounded px-3 py-2 leading-relaxed">
                            {t.answers?.[f.id]?.trim() || <span className="italic text-slate-400">— empty —</span>}
                          </div>
                        </div>
                      ))}
                    </div>
                  ) : <div className="caption italic mb-3">No answers yet.</div>
                ) : (
                  /* seg files */
                  t.submissions.length === 0 ? <div className="caption italic mb-3">No files uploaded yet.</div> : (
                    <div className="space-y-1 mb-3">
                      {[...segs, ...pngs].map((f, i) => (
                        <div key={i} className="flex items-center gap-2 px-2.5 py-1.5 bg-slate-50 border border-slate-200 rounded text-[11.5px]">
                          <span className="font-mono text-[9px] uppercase px-1.5 py-0.5 rounded bg-slate-200 text-slate-700">{f.kind === 'seg' ? 'SEG' : 'IMG'}</span>
                          <span className="font-mono text-slate-800 truncate flex-1">{f.filename}</span>
                          <span className="caption num">{formatBytes(f.size)}</span>
                        </div>
                      ))}
                    </div>
                  )
                )}

                <div className="flex items-center gap-2 pt-3 border-t border-slate-100">
                  {t.status === 'submitted' && (
                    <>
                      <button className="btn btn-sm btn-secondary" onClick={() => onStatusChange(t.id, 'accepted')}>✓ Accept</button>
                      <button className="btn btn-sm btn-danger" onClick={() => onStatusChange(t.id, 'revisions')}>Request revisions</button>
                    </>
                  )}
                  {t.status === 'accepted'  && <span className="caption text-emerald-700">✓ Accepted</span>}
                  {t.status === 'revisions' && <span className="caption text-red-700">Revisions requested</span>}
                  {(t.status === 'todo' || t.status === 'in_progress') && (
                    <button className="btn btn-sm btn-secondary" onClick={() => onStatusChange(t.id, 'submitted')}>Mark submitted</button>
                  )}
                </div>
              </article>
            )
          })}
        </div>

        <div className="px-6 py-3 caption border-t border-slate-200">esc to close</div>
      </div>
    </div>
  )
}
